data:
  dir: "~/elmnt/data"  # dir for storing downloaded files
  
binance:
  bucket_name: "data.binance.vision"  # binance historical data s3 bucket name

clickhouse:
  url: "http://localhost:8123"
  user: "default"
